build:
  image: rust:alpine
  variables:
    RUSTFLAGS: "-Ctarget-feature=+crt-static"
  script:
    - cargo build --release
    - strip --strip-all target/release/par-rmtree
  artifacts:
    paths:
      - target/release/par-rmtree
