[package]
name = "par-rmtree"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
clap = { version = "4.0", default-features = false, features = ["std", "help", "usage", "cargo"] }
glob = "0.3"
rayon = "1.5"

[profile.release]
lto = "thin"
strip = "debuginfo"
